<?php

use App\Http\Controllers\Admin\BookingController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Admin Home', 'section' => 'Overview', 'source' => 'client/app/admin/page.tsx', 'apiPath' => '/admin', 'params' => [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/dashboard', fn () => Inertia::render('Admin/Dashboard', [
        'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type']),
    ]))->name('dashboard');

    Route::middleware('permission:BOOKING_MANAGE')
        ->prefix('booking-management/bookings')
        ->name('booking-management.bookings.')
        ->group(function () {
            Route::get('/', [BookingController::class, 'index'])->name('index');
            Route::get('/{booking}', [BookingController::class, 'show'])->name('show');
            Route::post('/{booking}/assign-technician', [BookingController::class, 'assignTechnician'])->name('assign-technician');
        });

    Route::get('/masters/geography/areas/map', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Map', 'section' => 'Masters', 'source' => 'client/app/admin/masters/geography/areas/map/page.tsx', 'apiPath' => '/admin/masters/geography/areas/map', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/announcement-management/announcements', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Announcements', 'section' => 'Masters', 'source' => 'client/app/admin/masters/announcement-management/announcements/page.tsx', 'apiPath' => '/admin/masters/announcement-management/announcements', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/announcement-management/promotions', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Promotions', 'section' => 'Masters', 'source' => 'client/app/admin/masters/announcement-management/promotions/page.tsx', 'apiPath' => '/admin/masters/announcement-management/promotions', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/coupon-management/coupons', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Coupons', 'section' => 'Masters', 'source' => 'client/app/admin/masters/coupon-management/coupons/page.tsx', 'apiPath' => '/admin/masters/coupon-management/coupons', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/finance-management/charges', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Charges', 'section' => 'Masters', 'source' => 'client/app/admin/masters/finance-management/charges/page.tsx', 'apiPath' => '/admin/masters/finance-management/charges', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/finance-management/commissions', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Commissions', 'section' => 'Masters', 'source' => 'client/app/admin/masters/finance-management/commissions/page.tsx', 'apiPath' => '/admin/masters/finance-management/commissions', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/finance-management/discounts', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Discounts', 'section' => 'Masters', 'source' => 'client/app/admin/masters/finance-management/discounts/page.tsx', 'apiPath' => '/admin/masters/finance-management/discounts', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/finance-management/taxes', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Taxes', 'section' => 'Masters', 'source' => 'client/app/admin/masters/finance-management/taxes/page.tsx', 'apiPath' => '/admin/masters/finance-management/taxes', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/geography/areas', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Areas', 'section' => 'Masters', 'source' => 'client/app/admin/masters/geography/areas/page.tsx', 'apiPath' => '/admin/masters/geography/areas', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/geography/cities', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Cities', 'section' => 'Masters', 'source' => 'client/app/admin/masters/geography/cities/page.tsx', 'apiPath' => '/admin/masters/geography/cities', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/geography/countries', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Countries', 'section' => 'Masters', 'source' => 'client/app/admin/masters/geography/countries/page.tsx', 'apiPath' => '/admin/masters/geography/countries', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/geography/states', fn () => Inertia::render('Admin/PanelPage', ['title' => 'States', 'section' => 'Masters', 'source' => 'client/app/admin/masters/geography/states/page.tsx', 'apiPath' => '/admin/masters/geography/states', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/services-management/service-categories', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Service Categories', 'section' => 'Masters', 'source' => 'client/app/admin/masters/services-management/service-categories/page.tsx', 'apiPath' => '/admin/masters/services-management/service-categories', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/services-management/services', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Services', 'section' => 'Masters', 'source' => 'client/app/admin/masters/services-management/services/page.tsx', 'apiPath' => '/admin/masters/services-management/services', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/services-management/skills', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Skills', 'section' => 'Masters', 'source' => 'client/app/admin/masters/services-management/skills/page.tsx', 'apiPath' => '/admin/masters/services-management/skills', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/time-slot-management/time-slots', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Time Slots', 'section' => 'Masters', 'source' => 'client/app/admin/masters/time-slot-management/time-slots/page.tsx', 'apiPath' => '/admin/masters/time-slot-management/time-slots', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/support/tickets/new', fn () => Inertia::render('Admin/PanelPage', ['title' => 'New', 'section' => 'CRM & Support', 'source' => 'client/app/admin/support/tickets/new/page.tsx', 'apiPath' => '/admin/support/tickets/new', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/admin-management/admins', fn () => Inertia::render('Admin/AdminManagement/Admins/Index', ['admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/admin-management/menus', fn () => Inertia::render('Admin/AdminManagement/Menus/Index'));
    Route::get('/admin-management/permissions', fn () => Inertia::render('Admin/AdminManagement/Permissions/Index'));
    Route::get('/admin-management/roles', fn () => Inertia::render('Admin/AdminManagement/Roles/Index'));
    Route::get('/booking-management/workflow', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Workflow', 'section' => 'Booking Management', 'source' => 'client/app/admin/booking-management/workflow/page.tsx', 'apiPath' => '/admin/booking-management/workflow', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/cms/globals', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Globals', 'section' => 'CMS', 'source' => 'client/app/admin/cms/globals/page.tsx', 'apiPath' => '/admin/cms/globals', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/crm/analytics', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Analytics', 'section' => 'CRM & Support', 'source' => 'client/app/admin/crm/analytics/page.tsx', 'apiPath' => '/admin/crm/analytics', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/crm/complaints', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Complaints', 'section' => 'CRM & Support', 'source' => 'client/app/admin/crm/complaints/page.tsx', 'apiPath' => '/admin/crm/complaints', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/crm/customers', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Customers', 'section' => 'CRM & Support', 'source' => 'client/app/admin/crm/customers/page.tsx', 'apiPath' => '/admin/crm/customers', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/crm/spam', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Spam', 'section' => 'CRM & Support', 'source' => 'client/app/admin/crm/spam/page.tsx', 'apiPath' => '/admin/crm/spam', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/finance/failed', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Failed', 'section' => 'Finance', 'source' => 'client/app/admin/finance/failed/page.tsx', 'apiPath' => '/admin/finance/failed', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/finance/invoices', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Invoices', 'section' => 'Finance', 'source' => 'client/app/admin/finance/invoices/page.tsx', 'apiPath' => '/admin/finance/invoices', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/finance/payouts', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Payouts', 'section' => 'Finance', 'source' => 'client/app/admin/finance/payouts/page.tsx', 'apiPath' => '/admin/finance/payouts', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/finance/refunds', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Refunds', 'section' => 'Finance', 'source' => 'client/app/admin/finance/refunds/page.tsx', 'apiPath' => '/admin/finance/refunds', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/finance/reports', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Reports', 'section' => 'Finance', 'source' => 'client/app/admin/finance/reports/page.tsx', 'apiPath' => '/admin/finance/reports', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/finance/wallet', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Wallet', 'section' => 'Finance', 'source' => 'client/app/admin/finance/wallet/page.tsx', 'apiPath' => '/admin/finance/wallet', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/lookups/area-types', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Area Types', 'section' => 'Lookups', 'source' => 'client/app/admin/lookups/area-types/page.tsx', 'apiPath' => '/admin/lookups/area-types', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/lookups/booking-types', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Booking Types', 'section' => 'Lookups', 'source' => 'client/app/admin/lookups/booking-types/page.tsx', 'apiPath' => '/admin/lookups/booking-types', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/lookups/currencies', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Currencies', 'section' => 'Lookups', 'source' => 'client/app/admin/lookups/currencies/page.tsx', 'apiPath' => '/admin/lookups/currencies', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/lookups/document-types', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Document Types', 'section' => 'Lookups', 'source' => 'client/app/admin/lookups/document-types/page.tsx', 'apiPath' => '/admin/lookups/document-types', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/lookups/languages', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Languages', 'section' => 'Lookups', 'source' => 'client/app/admin/lookups/languages/page.tsx', 'apiPath' => '/admin/lookups/languages', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/lookups/payment-modes', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Payment Modes', 'section' => 'Lookups', 'source' => 'client/app/admin/lookups/payment-modes/page.tsx', 'apiPath' => '/admin/lookups/payment-modes', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/lookups/timezones', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Timezones', 'section' => 'Lookups', 'source' => 'client/app/admin/lookups/timezones/page.tsx', 'apiPath' => '/admin/lookups/timezones', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/lookups/units', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Units', 'section' => 'Lookups', 'source' => 'client/app/admin/lookups/units/page.tsx', 'apiPath' => '/admin/lookups/units', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/announcement-management', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Announcement Management', 'section' => 'Masters', 'source' => 'client/app/admin/masters/announcement-management/page.tsx', 'apiPath' => '/admin/masters/announcement-management', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters/pricing-rules', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Pricing Rules', 'section' => 'Masters', 'source' => 'client/app/admin/masters/pricing-rules/page.tsx', 'apiPath' => '/admin/masters/pricing-rules', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/notifications/broadcast', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Broadcast', 'section' => 'Notifications', 'source' => 'client/app/admin/notifications/broadcast/page.tsx', 'apiPath' => '/admin/notifications/broadcast', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/notifications/history', fn () => Inertia::render('Admin/PanelPage', ['title' => 'History', 'section' => 'Notifications', 'source' => 'client/app/admin/notifications/history/page.tsx', 'apiPath' => '/admin/notifications/history', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/notifications/logs', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Logs', 'section' => 'Notifications', 'source' => 'client/app/admin/notifications/logs/page.tsx', 'apiPath' => '/admin/notifications/logs', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/notifications/scheduled', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Scheduled', 'section' => 'Notifications', 'source' => 'client/app/admin/notifications/scheduled/page.tsx', 'apiPath' => '/admin/notifications/scheduled', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/notifications/templates', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Templates', 'section' => 'Notifications', 'source' => 'client/app/admin/notifications/templates/page.tsx', 'apiPath' => '/admin/notifications/templates', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/operations/audit', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Audit', 'section' => 'Operations', 'source' => 'client/app/admin/operations/audit/page.tsx', 'apiPath' => '/admin/operations/audit', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/operations/bookings', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Bookings', 'section' => 'Operations', 'source' => 'client/app/admin/operations/bookings/page.tsx', 'apiPath' => '/admin/operations/bookings', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/operations/live-dashboard', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Live Dashboard', 'section' => 'Operations', 'source' => 'client/app/admin/operations/live-dashboard/page.tsx', 'apiPath' => '/admin/operations/live-dashboard', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/security/2fa', fn () => Inertia::render('Admin/PanelPage', ['title' => '2fa', 'section' => 'Security', 'source' => 'client/app/admin/security/2fa/page.tsx', 'apiPath' => '/admin/security/2fa', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/security/alerts', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Alerts', 'section' => 'Security', 'source' => 'client/app/admin/security/alerts/page.tsx', 'apiPath' => '/admin/security/alerts', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/security/ip-rules', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Ip Rules', 'section' => 'Security', 'source' => 'client/app/admin/security/ip-rules/page.tsx', 'apiPath' => '/admin/security/ip-rules', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/security/sessions', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Sessions', 'section' => 'Security', 'source' => 'client/app/admin/security/sessions/page.tsx', 'apiPath' => '/admin/security/sessions', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/settings/notifications', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Notifications', 'section' => 'Settings', 'source' => 'client/app/admin/settings/notifications/page.tsx', 'apiPath' => '/admin/settings/notifications', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/settings/payments', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Payments', 'section' => 'Settings', 'source' => 'client/app/admin/settings/payments/page.tsx', 'apiPath' => '/admin/settings/payments', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/settings/profile', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Profile', 'section' => 'Settings', 'source' => 'client/app/admin/settings/profile/page.tsx', 'apiPath' => '/admin/settings/profile', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/support/categories', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Categories', 'section' => 'CRM & Support', 'source' => 'client/app/admin/support/categories/page.tsx', 'apiPath' => '/admin/support/categories', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/support/sla', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Sla', 'section' => 'CRM & Support', 'source' => 'client/app/admin/support/sla/page.tsx', 'apiPath' => '/admin/support/sla', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/support/tickets', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Tickets', 'section' => 'CRM & Support', 'source' => 'client/app/admin/support/tickets/page.tsx', 'apiPath' => '/admin/support/tickets', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/technician-management/applications', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Applications', 'section' => 'Technician Management', 'source' => 'client/app/admin/technician-management/applications/page.tsx', 'apiPath' => '/admin/technician-management/applications', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/technician-management/referrals', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Referrals', 'section' => 'Technician Management', 'source' => 'client/app/admin/technician-management/referrals/page.tsx', 'apiPath' => '/admin/technician-management/referrals', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/technician-management/technicians', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Technicians', 'section' => 'Technician Management', 'source' => 'client/app/admin/technician-management/technicians/page.tsx', 'apiPath' => '/admin/technician-management/technicians', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/transactions/invoices', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Invoices', 'section' => 'Transactions', 'source' => 'client/app/admin/transactions/invoices/page.tsx', 'apiPath' => '/admin/transactions/invoices', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/transactions/payments', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Payments', 'section' => 'Transactions', 'source' => 'client/app/admin/transactions/payments/page.tsx', 'apiPath' => '/admin/transactions/payments', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/transactions/payouts', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Payouts', 'section' => 'Transactions', 'source' => 'client/app/admin/transactions/payouts/page.tsx', 'apiPath' => '/admin/transactions/payouts', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/transactions/refunds', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Refunds', 'section' => 'Transactions', 'source' => 'client/app/admin/transactions/refunds/page.tsx', 'apiPath' => '/admin/transactions/refunds', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/transactions/taxes', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Taxes', 'section' => 'Transactions', 'source' => 'client/app/admin/transactions/taxes/page.tsx', 'apiPath' => '/admin/transactions/taxes', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/user-management/feedbacks', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Feedbacks', 'section' => 'User Management', 'source' => 'client/app/admin/user-management/feedbacks/page.tsx', 'apiPath' => '/admin/user-management/feedbacks', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/user-management/users', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Users', 'section' => 'User Management', 'source' => 'client/app/admin/user-management/users/page.tsx', 'apiPath' => '/admin/user-management/users', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/cms', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Cms', 'section' => 'CMS', 'source' => 'client/app/admin/cms/page.tsx', 'apiPath' => '/admin/cms', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/contact-inquiries', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Contact Inquiries', 'section' => 'CRM & Support', 'source' => 'client/app/admin/contact-inquiries/page.tsx', 'apiPath' => '/admin/contact-inquiries', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/crm', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Crm', 'section' => 'CRM & Support', 'source' => 'client/app/admin/crm/page.tsx', 'apiPath' => '/admin/crm', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/finance', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Finance', 'section' => 'Finance', 'source' => 'client/app/admin/finance/page.tsx', 'apiPath' => '/admin/finance', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/masters', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Masters', 'section' => 'Masters', 'source' => 'client/app/admin/masters/page.tsx', 'apiPath' => '/admin/masters', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/notifications', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Notifications', 'section' => 'Notifications', 'source' => 'client/app/admin/notifications/page.tsx', 'apiPath' => '/admin/notifications', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/reports', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Reports', 'section' => 'Reports', 'source' => 'client/app/admin/reports/page.tsx', 'apiPath' => '/admin/reports', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/security', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Security', 'section' => 'Security', 'source' => 'client/app/admin/security/page.tsx', 'apiPath' => '/admin/security', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/settings', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Settings', 'section' => 'Settings', 'source' => 'client/app/admin/settings/page.tsx', 'apiPath' => '/admin/settings', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/support', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Support', 'section' => 'CRM & Support', 'source' => 'client/app/admin/support/page.tsx', 'apiPath' => '/admin/support', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/tracker', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Tracker', 'section' => 'Operations', 'source' => 'client/app/admin/tracker/page.tsx', 'apiPath' => '/admin/tracker', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/user-management/users/{customerId}/create-booking', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Create Booking', 'section' => 'User Management', 'source' => 'client/app/admin/user-management/users/[customerId]/create-booking/page.tsx', 'apiPath' => '/admin/user-management/users/_id/create-booking', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/admin-management/admins/{adminId}', fn (string $adminId) => Inertia::render('Admin/AdminManagement/Admins/Show', ['adminId' => $adminId]));
    Route::get('/booking-management/workflow/{bookingId}', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Workflow Detail', 'section' => 'Booking Management', 'source' => 'client/app/admin/booking-management/workflow/[bookingId]/page.tsx', 'apiPath' => '/admin/booking-management/workflow/_id', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/crm/customers/{customerId}', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Customers Detail', 'section' => 'CRM & Support', 'source' => 'client/app/admin/crm/customers/[customerId]/page.tsx', 'apiPath' => '/admin/crm/customers/_id', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/support/tickets/{ticketId}', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Tickets Detail', 'section' => 'CRM & Support', 'source' => 'client/app/admin/support/tickets/[ticketId]/page.tsx', 'apiPath' => '/admin/support/tickets/_id', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/technician-management/technicians/{technicianId}', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Technicians Detail', 'section' => 'Technician Management', 'source' => 'client/app/admin/technician-management/technicians/[technicianId]/page.tsx', 'apiPath' => '/admin/technician-management/technicians/_id', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/user-management/users/{customerId}', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Users Detail', 'section' => 'User Management', 'source' => 'client/app/admin/user-management/users/[customerId]/page.tsx', 'apiPath' => '/admin/user-management/users/_id', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/cms/{slug}', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Cms Detail', 'section' => 'CMS', 'source' => 'client/app/admin/cms/[slug]/page.tsx', 'apiPath' => '/admin/cms/_id', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/contact-inquiries/{inquiryId}', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Contact Inquiries Detail', 'section' => 'CRM & Support', 'source' => 'client/app/admin/contact-inquiries/[inquiryId]/page.tsx', 'apiPath' => '/admin/contact-inquiries/_id', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
    Route::get('/user-management/users/{customerId}/bookings/{bookingId}', fn () => Inertia::render('Admin/PanelPage', ['title' => 'Bookings Detail', 'section' => 'User Management', 'source' => 'client/app/admin/user-management/users/[customerId]/bookings/[bookingId]/page.tsx', 'apiPath' => '/admin/user-management/users/_id/bookings/_id', 'params' => request()->route()?->parameters() ?? [], 'admin' => auth()->user()->only(['admin_id', 'first_name', 'last_name', 'email', 'admin_type'])]));
});