<?php

use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
 | Converted non-admin client route map generated from the old Next.js client.
 | Admin routes are handled by routes/admin.php.
 */

Route::get('profile/coupons', fn () => Inertia::render('ClientPage', ['title' => 'Coupons', 'source' => 'client/app/(user)/profile/coupons/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('profile/payments', fn () => Inertia::render('ClientPage', ['title' => 'Payments', 'source' => 'client/app/(user)/profile/payments/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('profile/referral', fn () => Inertia::render('ClientPage', ['title' => 'Referral', 'source' => 'client/app/(user)/profile/referral/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('technician/login', fn () => Inertia::render('ClientPage', ['title' => 'Login', 'source' => 'client/app/technician/login/page.tsx', 'area' => 'technician', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('technician/register', fn () => Inertia::render('ClientPage', ['title' => 'Register', 'source' => 'client/app/technician/register/page.tsx', 'area' => 'technician', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('about-us', fn () => Inertia::render('ClientPage', ['title' => 'About Us', 'source' => 'client/app/(public)/(landing)/(company)/about-us/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('account-deletion-policy', fn () => Inertia::render('ClientPage', ['title' => 'Account Deletion Policy', 'source' => 'client/app/(public)/(landing)/(legal)/account-deletion-policy/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('become-a-partner', fn () => Inertia::render('ClientPage', ['title' => 'Become A Partner', 'source' => 'client/app/(public)/(landing)/become-a-partner/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('bookings', fn () => Inertia::render('ClientPage', ['title' => 'Bookings', 'source' => 'client/app/(user)/bookings/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('cancellation-policy', fn () => Inertia::render('ClientPage', ['title' => 'Cancellation Policy', 'source' => 'client/app/(public)/(landing)/(legal)/cancellation-policy/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('cart', fn () => Inertia::render('ClientPage', ['title' => 'Cart', 'source' => 'client/app/(user)/cart/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('contact-us', fn () => Inertia::render('ClientPage', ['title' => 'Contact Us', 'source' => 'client/app/(public)/(landing)/(company)/contact-us/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('cookie-policy', fn () => Inertia::render('ClientPage', ['title' => 'Cookie Policy', 'source' => 'client/app/(public)/(landing)/(legal)/cookie-policy/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('disclaimer', fn () => Inertia::render('ClientPage', ['title' => 'Disclaimer', 'source' => 'client/app/(public)/(landing)/(legal)/disclaimer/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('faq', fn () => Inertia::render('ClientPage', ['title' => 'Faq', 'source' => 'client/app/(public)/(landing)/faq/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('grievance-policy', fn () => Inertia::render('ClientPage', ['title' => 'Grievance Policy', 'source' => 'client/app/(public)/(landing)/(legal)/grievance-policy/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('login', fn () => Inertia::render('ClientPage', ['title' => 'Login', 'source' => 'client/app/(auth)/login/page.tsx', 'area' => 'auth', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('offers', fn () => Inertia::render('ClientPage', ['title' => 'Offers', 'source' => 'client/app/(user)/offers/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('payment', fn () => Inertia::render('ClientPage', ['title' => 'Payment', 'source' => 'client/app/(user)/payment/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('privacy-policy', fn () => Inertia::render('ClientPage', ['title' => 'Privacy Policy', 'source' => 'client/app/(public)/(landing)/(legal)/privacy-policy/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('profile', fn () => Inertia::render('ClientPage', ['title' => 'Profile', 'source' => 'client/app/(user)/profile/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('refund-policy', fn () => Inertia::render('ClientPage', ['title' => 'Refund Policy', 'source' => 'client/app/(public)/(landing)/(legal)/refund-policy/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('safety-and-verification', fn () => Inertia::render('ClientPage', ['title' => 'Safety And Verification', 'source' => 'client/app/(public)/(landing)/(legal)/safety-and-verification/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('service-partner-agreement', fn () => Inertia::render('ClientPage', ['title' => 'Service Partner Agreement', 'source' => 'client/app/(public)/(landing)/(legal)/service-partner-agreement/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('services', fn () => Inertia::render('ClientPage', ['title' => 'Services', 'source' => 'client/app/(public)/services/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('services-in', fn () => Inertia::render('ClientPage', ['title' => 'Services In', 'source' => 'client/app/(public)/services-in/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('technician', fn () => Inertia::render('ClientPage', ['title' => 'Technician', 'source' => 'client/app/technician/page.tsx', 'area' => 'technician', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('terms-and-conditions', fn () => Inertia::render('ClientPage', ['title' => 'Terms And Conditions', 'source' => 'client/app/(public)/(landing)/(legal)/terms-and-conditions/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('warranty-policy', fn () => Inertia::render('ClientPage', ['title' => 'Warranty Policy', 'source' => 'client/app/(public)/(landing)/(legal)/warranty-policy/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('bookings/{bookingId}/track', fn () => Inertia::render('ClientPage', ['title' => 'Track', 'source' => 'client/app/(user)/bookings/[bookingId]/track/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('technician/{technicianId}/Completed-Jobs', fn () => Inertia::render('ClientPage', ['title' => 'Completed Jobs', 'source' => 'client/app/technician/[technicianId]/Completed-Jobs/page.tsx', 'area' => 'technician', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('technician/{technicianId}/dashboard', fn () => Inertia::render('ClientPage', ['title' => 'Dashboard', 'source' => 'client/app/technician/[technicianId]/dashboard/page.tsx', 'area' => 'technician', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('technician/{technicianId}/Earnings', fn () => Inertia::render('ClientPage', ['title' => 'Earnings', 'source' => 'client/app/technician/[technicianId]/Earnings/page.tsx', 'area' => 'technician', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('technician/{technicianId}/Job-Requests', fn () => Inertia::render('ClientPage', ['title' => 'Job Requests', 'source' => 'client/app/technician/[technicianId]/Job-Requests/page.tsx', 'area' => 'technician', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('technician/{technicianId}/profile', fn () => Inertia::render('ClientPage', ['title' => 'Profile', 'source' => 'client/app/technician/[technicianId]/profile/page.tsx', 'area' => 'technician', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('bookings/{bookingId}', fn () => Inertia::render('ClientPage', ['title' => 'BookingId', 'source' => 'client/app/(user)/bookings/[bookingId]/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('login/{uid}', fn () => Inertia::render('ClientPage', ['title' => 'Uid', 'source' => 'client/app/(auth)/login/[uid]/page.tsx', 'area' => 'auth', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('service/{serviceId}', fn () => Inertia::render('ClientPage', ['title' => 'ServiceId', 'source' => 'client/app/(user)/service/[serviceId]/page.tsx', 'area' => 'user', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('services-in/{city}', fn () => Inertia::render('ClientPage', ['title' => 'City', 'source' => 'client/app/(public)/services-in/[city]/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('{slug}', fn () => Inertia::render('ClientPage', ['title' => 'Slug', 'source' => 'client/app/(public)/(landing)/[slug]/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('services-in/{city}/{service}', fn () => Inertia::render('ClientPage', ['title' => 'Service', 'source' => 'client/app/(public)/services-in/[city]/[service]/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('{slug}/{service}', fn () => Inertia::render('ClientPage', ['title' => 'Service', 'source' => 'client/app/(public)/(seo)/[slug]/[service]/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('services-in/{city}/{service}/{detail}', fn () => Inertia::render('ClientPage', ['title' => 'Detail', 'source' => 'client/app/(public)/services-in/[city]/[service]/[detail]/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));
Route::get('{slug}/{service}/{detail}', fn () => Inertia::render('ClientPage', ['title' => 'Detail', 'source' => 'client/app/(public)/(seo)/[slug]/[service]/[detail]/page.tsx', 'area' => 'public', 'path' => request()->path(), 'params' => request()->route()?->parameters() ?? []]));